### ISSUE TITLE
Data field in a relocatable file received *ERROR: Attempt to overwrite address 0h

### ISSUE THREAD

**Issue by fourstix** [wd5gnr/Asm-02#3]
I have a library that has a data field in a relocatable module.  The Assembler assigns the field's address as 0 in the .prg file and later the linker will supply the actual address.  

When I assembled the lcd_send_cmd file with the following command
C:\Asm02\asm02 -L -D1802MINIPLUS lcd_send_cmd.asm

I received the following output:

Asm/02 v1.5
by Michael H. Riley
lcd_send_cmd.asm:91: *ERROR: Attempt to overwrite address 0h
   91 |             db LCD_CMD          ; default command bits (RS off, Backlight on)

Lines Assembled   : 735
Code Generated    : 65
Errors            : 1

I don't think this should be flagged as an error since the code is relocatable and this data field will not over-lap any existing address.
I'm not sure if the over-write check should not be done on relocatable modules, as the actual location isn't know until the it's assigned by the liner.

The source file lcd_send_cmd.asm is attached with the txt extension added.

[lcd_send_cmd.asm.txt](https://github.com/wd5gnr/Asm-02/files/12566552/lcd_send_cmd.asm.txt)

**Comment by wd5gnr** [comment]
I think this was fixed upstream and was an artifact of the upstream changes. My code should not have overlap checked at all when -R was in effect.

**Comment by fourstix** [comment]
Yes.  Tony has fixed this issue in his latest version which merged in these changes.  I am now using the code from his updates branch and it works fine.  So I'll go ahead and close this issue.
